### PR TITLE
Implement Form Validation at Backend Register

### PR DESCRIPTION
**Pull request by 2bit-hack**
Issue #2 

Used Regular Expressions to validate passwords and email addresses. Created a `validators` folder with a file called `validators.js` that contains the validator functions. Tested validator Regexes with various inputs.

Integrated the validators into `routes/api/users.js`, running them before registration, and returning error codes with messages in case the validator check fails.

### CODE REVIEW

**Review by hyperloo — CHANGES_REQUESTED** [review]
Please remove package-lock.json

**Comment by 2bit-hack** [comment]
Should I also add that to gitignore?

**Review by hyperloo — CHANGES_REQUESTED** [review]
Please remove package-lock.json

**Comment by 2bit-hack** [comment]
package-lock.json is not amongst the files changed

**Comment by hyperloo** [comment]
> 
> 
> package-lock.json is not amongst the files changed

I think you have removed the package-lock.json in the third commit. Am I right? If so, then it is fine.

**Comment by 2bit-hack** [comment]
Yeah, added in the first commit, then removed later.

**Comment by hyperloo** [comment]
> ater.

Then that's fine. 🙂

**Review by hyperloo — APPROVED** [review]

**Comment by hyperloo** [comment]
Functioning Properly. 🙂
Merging your PR.

**Comment by hyperloo** [comment]
Hey, Star this repo! 😁

**Pull request merged**
